config/routes.rb
Rails.application.routes.draw do
  # get "/users/new", to: "users#new"
  # post "/users/create", to: "users#create"
  resources :users, only: [:index, :new, :create]
  
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :nick_name, {presence: true, uniqueness: true}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(nick_name: params[:nick_name])
    if @user.save
      redirect_to root_path, notice: '登録しました'
    else
      render :new
    end

  end

  # private

  # def user_params
  #   params.require(:user).permit(:nick_name)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CounterattackTapioca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="text-center mt-3">
  <h1 class="mb-5">ユーザー一覧</h1>
  <%= link_to '新規登録', new_user_path, class: 'btn btn-outline-primary mt-3 mb-5' %>
  <br>
  <% @users.each do |user| %>
    <%= user.nick_name %><span>さん</span>
    <p>---------------------</p>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="col-md-8 offset-md-2 mt-5">
  <div class="user-box">
    <h1 class="text-center">新規登録</h1>
    <%= form_with url: users_path, local: true do |f| %>
      <div class="form-group">
        <%= f.label :nick_name, 'ニックネーム' %>
        <%= f.text_field :nick_name, class: 'form-control' %>
      </div>
      <%= f.submit '登録する', class: 'btn btn-outline-primary mb-2' %>
    <% end %>
      <%= link_to 'ユーザー一覧', root_path, class: 'btn btn-outline-primary' %>
  </div>
</div>